language: node_js
node_js:
  - stable
before_script:
  - npm install connect
  - npm install serve-static
  - ls
  - sudo $(which node) test/js/server.js &
  - sleep 5
script: phantomjs test/qunit/run-qunit.js 'http://localhost:80/test/index.html'