language: node_js
node_js:
  - stable
before_script:
  - mkdir ../lib
  - mkdir ../lib/candy-calc
  - mv * .[^.]* ../lib/candy-calc/
  - cd ..
  - npm install connect
  - npm install serve-static
  - npm install qunit-phantomjs-runner
  - ls
  - sudo $(which node) lib/candy-calc/test/js/server.js &
  - sleep 5
script: phantomjs node_modules/qunit-phantomjs-runner/runner.js 'http://localhost:80/lib/candy-calc/test/index.html'