language: node_js
node_js:
  - stable
before_script:
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - ls
  - cd project
  - sudo node test/js/server.js &
  - sleep 20
script: phantomjs test/qunit/run-qunit.js 'http://localhost:80/test/index.html'